[versions]
androidx-lifecycle = "2.10.0-alpha06"
# https://github.com/JetBrains/compose-multiplatform
compose-plugin = "1.10.0"
compose-material3 = "1.9.0"
compose-material-icons = "1.7.3"
junit = "4.13.2"
kotlin = "2.3.0"
kotlin-coroutine = "1.10.2"
kotlin-browser = "0.5"
kotlin-serialization = "1.9.0"
#ktor = "3.1.3"

codegentle = "0.0.3"

# 代码高亮
## https://github.com/SnipMeDev/Highlights
highlights = "1.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlin-coroutine = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
# https://github.com/kotlin/kotlinx-browser
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin-browser" }


# ktor
# 直接用的fetch，因为之前用ktor的wasm有bug
#ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
#ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
#ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# composes
jb-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-plugin" }
jb-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-plugin" }
jb-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
jb-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-plugin" }
jb-compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-material-icons" }
jb-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-plugin" }
jb-compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-plugin" }
## ICON https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose-180.html#implicit-dependency-on-material-icons-core-removed

# kotlin serialization
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

# CodeGentle
codegentle-kotlin = { module = "love.forte.codegentle:codegentle-kotlin", version.ref = "codegentle" }
codegentle-java = { module = "love.forte.codegentle:codegentle-java", version.ref = "codegentle" }

highlights = { module = "dev.snipme:highlights", version.ref = "highlights" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
